export const manifest = {
  "IMG_0219.jpg": {
    artist: "Valeria Perez-Rebollar",
    grade: 10,
    materials: "Colored pencil, pen, pencil, acrylic",
    description: "Class: MultiMedia I",
    year: 2022,
  },
  "IMG_0220.jpg": {
    artist: "Iris Anderson",
    grade: 11,
    materials: "Acrylic",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "IMG_0221.jpg": {
    artist: "Talia Lewis",
    grade: 10,
    materials: "Acrylic, collage, chalk pastel",
    description: "Class: MultiMedia I",
    year: 2022,
  },
  "IMG_0222.jpg": {
    artist: "Valeria Perez-Rebollar",
    grade: 10,
    materials: "Acrylic, string, buttons",
    description: "Class: Multimedia I",
    year: 2022,
  },
  "IMG_0223.jpg": {
    artist: "Mila Cardenas",
    grade: 11,
    materials: "Pen, pencil, collage",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "IMG_0224.jpg": {
    artist: "Cole Ryan",
    grade: 10,
    materials: "Pen, sharpie, acrylic, collage",
    description: "Class: Multimedia I",
    year: 2022,
  },
  "IMG_0225.jpg": {
    artist: "Leila Cruz",
    grade: 11,
    materials: "Acrylic, pen, sharpie",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "IMG_0226.jpg": {
    artist: "Cole Ryan",
    grade: 10,
    materials: "Watercolor, tracing paper, construction paper, pen",
    description: "Class: Multimedia I",
    year: 2022,
  },
  "IMG_0227.jpg": {
    artist: "Janette Ramirez",
    grade: 10,
    materials: "Acrylic, block-printing",
    description: "Class: Multimedia I",
    year: 2023,
  },
  "IMG_0228.jpg": {
    artist: "Iris Anderson",
    grade: 11,
    materials: "Acrylic, collage",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "IMG_0229.jpg": {
    artist: "Iris Anderson",
    grade: 11,
    materials: "Colored pencil",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "IMG_5480.jpg": {
    artist: "Nelly Villegas",
    grade: 11,
    materials: "Colored pencil, sharpie, acrylic",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },

  "IMG_6358.JPG": {
    artist: "Natalie Ortega",
    grade: 9,
    materials: "Digital photo, self-portrait",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_6359.JPG": {
    artist: "Habtamu Regasa",
    grade: 12,
    materials: "Digital photo, self-portrait",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_6391.jpg": {
    artist: "Melvin Hughes",
    grade: 9,
    materials: "Digital photo, self-portrait",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_7418.jpg": {
    artist: "Judy Kou",
    grade: 11,
    materials: "Acrylic, paper mache, cardboard, ribbon",
    description: "Class: Multimedia II",
    year: 2018,
  },
  "IMG_7659.JPG": {
    artist: "Quinn Moreno",
    grade: 10,
    materials: "Aluminum cans, newspaper",
    description: "Class: Multimedia I",
    year: 2019,
  },
  "IMG_7661.JPG": {
    artist: "Naima Woods",
    grade: 11,
    materials: "Acrylic on jacket",
    description: "Class: Art II",
    year: 2019,
  },
  "Subject.jpg": {
    artist: "Jelly Rodriguez",
    grade: 10,
    materials: "Acrylic, buttons, glitter",
    description: "Class: Multimedia I",
    year: 2022,
  },
  "YaretzyGonzalez2.jpg": {
    artist: "Yaretzy Gonzalez",
    grade: 11,
    materials: "Acrylic",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "CosmoGraff4.jpg": {
    artist: "Cosmo Graff",
    grade: 11,
    materials: "acrylic, colored pencil",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "CosmoGraff5.jpg": {
    artist: "Cosmo Graff",
    grade: 11,
    materials: "acrylic, marker, string, shrinky-dinks",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "ThaliaKouchoukos12.jpg": {
    artist: "Thalia Kouchoukos",
    grade: 11,
    materials: "ink, pencil",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },

  "ThaliaKouchoukos3.jpg": {
    artist: "Thalia Kouchoukos",
    grade: 11,
    materials: "ink, pen",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "Lesly Sanchez1.jpg": {
    artist: "Lesly Sanchez",
    grade: 11,
    materials: "pencil, acrylic, oil pastel",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "Lesly Sanchez2.jpg": {
    artist: "Lesly Sanchez",
    grade: 11,
    materials: "pencil",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
};
