export const manifest = {
  "IMG_0225.jpg": {
    artist: "Leila Cruz",
    grade: 11,
    materials: "Acrylic, pen, sharpie",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "IMG_0226.jpg": {
    artist: "Cole Ryan",
    grade: 10,
    materials: "Watercolor, tracing & construction paper, pen",
    description: "Class: Multimedia I",
    year: 2022,
  },
  "IMG_0227.jpg": {
    artist: "Janette Ramirez",
    grade: 10,
    materials: "Acrylic, block-printing",
    description: "Class: Multimedia I",
    year: 2023,
  },
  "IMG_0228.jpg": {
    artist: "Iris Anderson",
    grade: 11,
    materials: "Acrylic, collage",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "IMG_0229.jpg": {
    artist: "Iris Anderson",
    grade: 11,
    materials: "Colored pencil",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "IMG_0229(1).jpg": {
    artist: "Lesly Sanchez",
    grade: 11,
    materials: "Pencil, acrylic, pen",
    description: "Class: AP-2D Art & Design",
    year: 2022,
  },
  "IMG_0230.jpg": {
    artist: "Ta'Kirah King",
    grade: 10,
    materials: "Acrylic, block-printing, yarn",
    description: "Class: Multimedia I",
    year: 2023,
  },
  "IMG_5480.jpg": {
    artist: "Nelly Villegas",
    grade: 11,
    materials: "Colored pencil, sharpie, acrylic",
    description: "Class: AP-2D Art & Design",
    year: 2023,
  },
  "IMG_6358.jpg": {
    artist: "Natalie Ortega",
    grade: 9,
    materials: "Digital self-portrait",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_6359.jpg": {
    artist: "Habtamu Regasa",
    grade: 12,
    materials: "Digital self-portrait",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_6391.jpg": {
    artist: "Melvin Hughes",
    grade: 9,
    materials: "Digital self-portrait",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_7395.jpg": {
    artist: "Max Evans",
    grade: 12,
    materials: "Acrylic on pants",
    description: "Class: Art I",
    year: 2019,
  },
  "IMG_7418.jpg": {
    artist: "Judy Kou",
    grade: 11,
    materials: "Acrylic, paper maché, cardboard, ribbon",
    description: "Class: Multimedia II",
    year: 2018,
  },
  "IMG_7659.jpg": {
    artist: "Quinn Moreno",
    grade: 10,
    materials: "Aluminum cans, newspaper",
    description: "Class: Multimedia I",
    year: 2019,
  },
  "IMG_7661.jpg": {
    artist: "Naima Woods",
    grade: 12,
    materials: "Acrylic on jacket",
    description: "Class: Art II",
    year: 2019,
  },
  "Subject.jpg": {
    artist: "Jelly Rodriguez",
    grade: 10,
    materials: "Acrylic, buttons, glitter",
    description: "Class: Multimedia I",
    year: 2022,
  },
};
